### ISSUE TITLE
是不是少写了啥

### ISSUE THREAD

**Issue by shenjackyuanjie** [eagle3236/daycount-NBT#4]
https://github.com/alex3236/daycount-NBT/blob/6d21effd9ef7039c69cf1cc9a63a72643a2b4d56/src/daycount_nbt/__init__.py?_pjax=%23js-repo-pjax-container#L18

发现一个`['']`
捉住！

**Comment by alex3236** [comment]
哦我的上帝啊，这真不是我的错，你应该怪 nbtlib (doge)

**Comment by shenjackyuanjie** [comment]
太屑了*
